### ISSUE TITLE
Instantiating with session name throws error

### ISSUE THREAD

**Issue by tinnvec** [CleverbotIO/ruby-cleverbot.io#4]
When calling `Cleverbot.new('USER', 'KEY', 'sessionname')`, the following error is thrown, if the same session name has ever been used:

> vendor/bundle/gems/cleverbot_io-1.2.2/lib/cleverbot.rb:60:in `try_throw': Reference name already exists. (Cleverbot::Errors::DuplicatedReferenceNamesError)

calling `Cleverbot.new` without a session name (and setting the nick afterward) works as expected.

**Comment by elifoster** [comment]
Well, the API returns `Error: reference name already exists` when you do that. Not really sure what was the expected behavior here.

**Comment by tinnvec** [comment]
I apologize, perhaps I misunderstood the use of session name. I was under the impression it was used in a way that the session could be reconnected to (or 'resumed', as it were). Kind of like continuing the same conversation.

**Comment by elifoster** [comment]
Oh, I'm not saying that it's _good_ behavior. That's just what happens if you do that in the API :P

**Comment by tinnvec** [comment]
Ah, sorry for the confusion. Looking at the code more, I see that the nick will still get passed to the API in the say method, so setting after the fact (but before say) should accomplish what I was thinking I was doing at first.

Thank you for the lightning fast responses!

**Comment by dtesler** [comment]
Apologies for not being able to comment on this before: This is an issue that we're aware of and we're actually working on building a new API to address this issue and others. -- Feel free to hit me up on the [cleverbot.io slack](https://slack.cleverbot.io) if you have any other issues.
